# Generated by Django 3.0.7 on 2020-06-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200610_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='балл',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='введение',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='имя',
        ),
    ]
