# Generated by Django 3.0.7 on 2020-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200613_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='балл',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
