# Generated by Django 3.0.7 on 2020-06-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_introduction_балл'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a_вариант',
        ),
        migrations.RemoveField(
            model_name='question',
            name='б_вариант',
        ),
        migrations.RemoveField(
            model_name='question',
            name='в_вариант',
        ),
        migrations.RemoveField(
            model_name='question',
            name='г_вариант',
        ),
        migrations.RemoveField(
            model_name='question',
            name='д_вариант',
        ),
    ]
