# Generated by Django 3.0.7 on 2020-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200614_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='объяснение',
        ),
        migrations.AddField(
            model_name='question',
            name='a_вариант',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='б_вариант',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='в_вариант',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='г_вариант',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='д_вариант',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
